version: '3.0'
services:
  db:
    container_name: ctfdbcontainer
    build: .
    healthcheck:
      test: pg_isready -d comp6841db -U postgres -p 5432
      interval: 10s
      timeout: 30s
      retries: 3
      start_period: 10s
  ctf_app:
    container_name: ctfappcontainer
    build: ./ctf
    links:
      - "db:database"
    ports:
      - "5000:5000" # docker container 5000, access from 5000 localhost
    depends_on:
      db:
        condition: service_healthy



